server:
  port: 80
  servlet:
    context-path: /api


spring:
  jackson:
    serialization.write-dates-as-timestamps: false
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd hh:mm:ss
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE:study-record}
    username: ${MYSQL_USERNAME}
    password: ${MySQL_PASSWORD}
  web.resources.add-mappings: false
  mvc:
    view:
      suffix: .html
      prefix: /
    throw-exception-if-no-handler-found: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      capitalMode: true
      table-underline: false

#  微信小程序配置 appid /appsecret
wx:
  applet:
    appid: ${APP_ID}
    appsecret: ${APP_SECRET}
